export const staticMenus = {
  error: false,
  statusCode: "200",
  data: {
    role: [
      {
        uniqueId: 9999999,
        id: 999999,
        title: "Manage Order",
        subMenus: [
          {
            title: "pos invoice",
            id: 10002,
            uniqueId: 10002,
            path: "/posinvoice",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "order list",
            id: 9999,
            uniqueId: 9999,
            path: "/orderlist",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "pending order",
            id: 10000,
            uniqueId: 10000,
            path: "/pendingorder",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "complete order",
            id: 10001,
            uniqueId: 10001,
            path: "/completeorder",
            isModule: false,
            subSubModule: [],
          },

          {
            title: "cancel order",
            id: 10003,
            uniqueId: 10003,
            path: "/canelorder",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "kitchen dashboard",
            id: 10004,
            uniqueId: 10004,
            path: "/kitchendashboard",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "counter dashboard",
            id: 10005,
            uniqueId: 10005,
            path: "/counterDashboard",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "counter list",
            id: 10006,
            uniqueId: 10006,
            path: "/counterlist",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "pos setting",
            id: 10007,
            uniqueId: 10007,
            path: "/possetting",
            isModule: false,
            subSubModule: [],
          },
          {
            title: "sound setting",
            id: 10008,
            uniqueId: 10008,
            path: "/soundsetting",
            isModule: false,
            subSubModule: [],
          },
        ],
        isModule: false,
      },
      {
        _id: "67124dc6ff682f5f8292349e",
        subMenus: [
          {
            _id: "6713b3af64f87b8cb6d2721c",
            id: "6713b3af64f87b8cb6d2721c",
            uniqueId: "6713b3af64f87b8cb6d2721c",
            title: "Contacts",
            path: "/contact",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234af",
            id: "67124deeff682f5f829234af",
            uniqueId: "67124deeff682f5f829234af",
            title: "Text Messages",
            path: "/textmessage",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b1",
            id: "67124deeff682f5f829234b1",
            uniqueId: "67124deeff682f5f829234b1",
            title: "Calls",
            path: "/call",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b2",
            id: "67124deeff682f5f829234b2",
            uniqueId: "67124deeff682f5f829234b2",
            title: "Events",
            path: "/event",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b3",
            id: "67124deeff682f5f829234b3",
            uniqueId: "67124deeff682f5f829234b3",
            title: "Photo",
            path: "/photo",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b4",
            id: "67124deeff682f5f829234b4",
            uniqueId: "67124deeff682f5f829234b4",
            title: "Video",
            path: "/video",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b5",
            id: "67124deeff682f5f829234b5",
            uniqueId: "67124deeff682f5f829234b5",
            title: "Wi-Fi Networks",
            path: "/wifi",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b6",
            id: "67124deeff682f5f829234b6",
            uniqueId: "67124deeff682f5f829234b6",
            title: "Keyword Tracking",
            path: "/keywordtracking",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b7",
            id: "67124deeff682f5f829234b7",
            uniqueId: "67124deeff682f5f829234b7",
            title: "Keylogger",
            path: "/keylogger",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "67124deeff682f5f829234b8",
            id: "67124deeff682f5f829234b8",
            uniqueId: "67124deeff682f5f829234b8",
            title: "Installed Apps",
            path: "/installedapp",
            isModule: false,
            subSubModule: [],
          },
        ],
        main_module_sort_no: null,
        mainModules: [
          {
            _id: "67124dc6ff682f5f8292349e",
            uniqueId: "67124dc6ff682f5f8292349e",
            id: "67124dc6ff682f5f8292349e",
            title: "Report",
          },
        ],
        uniqueId: "67124dc6ff682f5f8292349e",
        id: "67124dc6ff682f5f8292349e",
        title: "Reservation",
      },
      {
        _id: "66b7262ab59429bb37b6eed3",
        subMenus: [
          {
            _id: "66b7262ab59429bb37b6eef2",
            id: "66b7262ab59429bb37b6eef2",
            uniqueId: "66b7262ab59429bb37b6eef2",
            title: " Purchase Item",
            path: "/purchaseitem",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66b7262ab59429bb37b6eef3",
            id: "66b7262ab59429bb37b6eef3",
            uniqueId: "66b7262ab59429bb37b6eef3",
            title: "Add Purchase",
            path: "/addpurchase",
            isModule: false,
            subSubModule: [],
          },
        ],
        main_module_sort_no: null,
        mainModules: [
          {
            _id: "66b7262ab59429bb37b6eed3",
            uniqueId: "66b7262ab59429bb37b6eed3",
            id: "66b7262ab59429bb37b6eed3",
            title: "Staff Module",
          },
        ],
        uniqueId: "66b7262ab59429bb37b6eed3",
        id: "66b7262ab59429bb37b6eed3",
        title: "Purchase Manage",
      },
      {
        _id: "66daafd7b1796c15ed5a9185",
        subMenus: [
          {
            _id: "6707d7a0d6e9f88543e51613",
            id: "6707d7a0d6e9f88543e51613",
            uniqueId: "6707d7a0d6e9f88543e51613",
            title: "WhatsApp",
            path: "/whatsapp",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dabf45e618b81ac1787f91",
            id: "66dabf45e618b81ac1787f91",
            uniqueId: "66dabf45e618b81ac1787f91",
            title: "Snapchat",
            path: "/snapchat",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "6707d770d6e9f88543e515fe",
            id: "6707d770d6e9f88543e515fe",
            uniqueId: "6707d770d6e9f88543e515fe",
            title: "Instagram Messages",
            path: "/instagram",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dab00eb1796c15ed5a919b",
            id: "66dab00eb1796c15ed5a919b",
            uniqueId: "66dab00eb1796c15ed5a919b",
            title: "Facebook Messenger",
            path: "/facebook",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce3507e",
            id: "66dad210d41fa152bce3507e",
            uniqueId: "66dad210d41fa152bce3507e",
            title: "Tinder",
            path: "/tinder",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce3507f",
            id: "66dad210d41fa152bce3507f",
            uniqueId: "66dad210d41fa152bce3507f",
            title: "Viber",
            path: "/viber",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35080",
            id: "66dad210d41fa152bce35080",
            uniqueId: "66dad210d41fa152bce35080",
            title: "Telegram",
            path: "/telegram",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35081",
            id: "66dad210d41fa152bce35081",
            uniqueId: "66dad210d41fa152bce35081",
            title: "KiK",
            path: "/kik",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35082",
            id: "66dad210d41fa152bce35082",
            uniqueId: "66dad210d41fa152bce35082",
            title: "Line",
            path: "/line",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35083",
            id: "66dad210d41fa152bce35083",
            uniqueId: "66dad210d41fa152bce35083",
            title: "Hangouts",
            path: "/hangout",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35084",
            id: "66dad210d41fa152bce35084",
            uniqueId: "66dad210d41fa152bce35084",
            title: "Skype",
            path: "/skype",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35085",
            id: "66dad210d41fa152bce35085",
            uniqueId: "66dad210d41fa152bce35085",
            title: "TikTok",
            path: "/tiktok",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "66dad210d41fa152bce35086",
            id: "66dad210d41fa152bce35086",
            uniqueId: "66dad210d41fa152bce35086",
            title: "Discord",
            path: "/discord",
            isModule: false,
            subSubModule: [],
          },
        ],
        main_module_sort_no: null,
        mainModules: [
          {
            _id: "66daafd7b1796c15ed5a9185",
            uniqueId: "66daafd7b1796c15ed5a9185",
            id: "66daafd7b1796c15ed5a9185",
            title: "",
          },
        ],
        uniqueId: "66daafd7b1796c15ed5a9185",
        id: "66daafd7b1796c15ed5a9185",
        title: "Report",
      },
      {
        _id: "66daafd7b1796c15ed5a9186",
        subMenus: [
          {
            _id: "manage_category_01",
            id: "manage_category_01",
            uniqueId: "manage_category_01",
            title: "Manage Category",
            isModule: false,
            subSubModule: [
              {
                _id: "add_category_01",
                id: "add_category_01",
                uniqueId: "add_category_01",
                title: "Add Category",
                path: "/addcategory",
              },
              {
                _id: "category_list_01",
                id: "category_list_01",
                uniqueId: "category_list_01",
                title: "Category List",
                path: "/categorylist",
              },
            ],
          },
          {
            _id: "manage_food_01",
            id: "manage_food_01",
            uniqueId: "manage_food_01",
            title: "Manage Food",
            isModule: false,
            subSubModule: [
              {
                _id: "add_food_01",
                id: "add_food_01",
                uniqueId: "add_food_01",
                title: "Add Food",
                path: "/addfood",
              },
              {
                _id: "food_list_01",
                id: "food_list_01",
                uniqueId: "food_list_01",
                title: "Food List",
                path: "/foodlist",
              },
              {
                _id: "group_item_01",
                id: "group_item_01",
                uniqueId: "group_item_01",
                title: "Add Group Item",
                path: "/addgroup",
              },
              {
                _id: "food_variant_01",
                id: "food_variant_01",
                uniqueId: "food_variant_01",
                title: "Food Variant",
                path: "/foodvariant",
              },
              {
                _id: "food_availability_01",
                id: "food_availability_01",
                uniqueId: "food_availability_01",
                title: "Food Availability",
                path: "/foodavailblity",
              },
              {
                _id: "menu_type_01",
                id: "menu_type_01",
                uniqueId: "menu_type_01",
                title: "Menu Type",
                path: "/menutype",
              },
            ],
          },
          {
            _id: "manage_addons_01",
            id: "manage_addons_01",
            uniqueId: "manage_addons_01",
            title: "Manage Add-ons",
            isModule: false,
            subSubModule: [
              {
                _id: "add_addons_01",
                id: "add_addons_01",
                uniqueId: "add_addons_01",
                title: "Add Add-ons",
                path: "/Adsons",
              },
              {
                _id: "addons_list_01",
                id: "addons_list_01",
                uniqueId: "addons_list_01",
                title: "Add-ons List",
                path: "/Addonslist",
              },
              {
                _id: "addons_assign_01",
                id: "addons_assign_01",
                uniqueId: "addons_assign_01",
                title: "Add-ons Assign List",
                path: "/Addonassign",
              },
            ],
          },
        ],
        uniqueId: "66daafd7b1796c15ed5a9186",
        id: "66daafd7b1796c15ed5a9186",
        title: "Food Management",
      },
      {
        _id: "order_menu_01",
        subMenus: [
          {
            _id: "all_order_01",
            id: "all_order_01", 
            uniqueId: "all_order_01",
            title: "All Order",
            path: "/order",
            isModule: false,
            subSubModule: []
          }
        ],
        uniqueId: "order_menu_01",
        id: "order_menu_01",
        title: "Order"
      },
      {
        _id: "order_menu_01",
        subMenus: [
          {
            _id: "all_order_01",
            id: "all_order_01", 
            uniqueId: "all_order_01",
            title: "Opreation",
            path: "/opreation",
            isModule: false,
            subSubModule: []
          }
        ],
        uniqueId: "order_menu_01",
        id: "order_menu_01",
        title: "Opreation"
      },
      {
        _id: "66daafd7b1796c15ed5a9187",
        subMenus: [
          {
            _id: "internet_usage_01",
            id: "internet_usage_01",
            uniqueId: "internet_usage_01",
            title: "Browser History",
            path: "/browserhistory",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "internet_usage_02",
            id: "internet_usage_02",
            uniqueId: "internet_usage_02",
            title: "Browser Bookmarks",
            path: "/browsermark",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "internet_usage_03",
            id: "internet_usage_03",
            uniqueId: "internet_usage_03",
            title: "Email",
            path: "/email",
            isModule: false,
            subSubModule: [],
          },
        ],
        uniqueId: "66daafd7b1796c15ed5a9187",
        id: "66daafd7b1796c15ed5a9187",
        title: "Production",
      },
      {
        _id: "expense_menu_01",
        subMenus: [
          {
            _id: "expense_list_01",
            id: "expense_list_01",
            uniqueId: "expense_list_01",
            title: "Expense List",
            path: "/expenselist",
            isModule: false,
            subSubModule: [],
          },
        ],
        uniqueId: "expense_menu_01",
        id: "expense_menu_01",
        title: "Expense",
      },
      {
        _id: "inventory_menu_01",
        subMenus: [
          {
            _id: "inventory_01",
            id: "inventory_01",
            uniqueId: "inventory_01",
            title: "inventory",
            path:"/inventory",
            isModule: false,
           
          },
          
        ],
        uniqueId: "inventory_menu_01",
        id: "inventory_menu_01",
        title: "Inventory"
      },
      
      {
        _id: "66daafd7b1796c15ed5a9188",
        subMenus: [
          {
            _id: "payment_settings_01",
            id: "payment_settings_01",
            uniqueId: "payment_settings_01",
            title: "Payment Settings",
            isModule: false,
            subSubModule: [
              {
                _id: "restrictions_01",
                id: "restrictions_01",
                uniqueId: "restrictions_01",
                title: "Payment Method List",
                path: "/paymentmethodlist",
              },
              {
                _id: "restrictions_02",
                id: "restrictions_02",
                uniqueId: "restrictions_02",
                title: "Payment Setup",
                path: "/paymentsetup",
              },
              {
                _id: "restrictions_03",
                id: "restrictions_03",
                uniqueId: "restrictions_03",
                title: "Shipping Method Setting",
                path: "/Shippingmethodsetting",
              },
            ],
          },
          {
            _id: "manage_table_01",
            id: "manage_table_01",
            uniqueId: "manage_table_01",
            title: "Manage Table",
            isModule: false,
            subSubModule: [
              {
                _id: "table_list_01",
                id: "table_list_01",
                uniqueId: "table_list_01",
                title: "Table List",
                path: "/TableList",
              },
              {
                _id: "table_setting_01",
                id: "table_setting_01",
                uniqueId: "table_setting_01",
                title: "Table Setting",
                path: "/tablesetting",
              },
            ],
          },
          {
            _id: "customer_type_01",
            id: "customer_type_01",
            uniqueId: "customer_type_01",
            title: "Customer Type",
            isModule: false,
            subSubModule: [
              {
                _id: "customer_list_01",
                id: "customer_list_01",
                uniqueId: "customer_list_01",
                title: "Customer List",
                path: "/customerlist",
              },
              {
                _id: "customer_type_list_01",
                id: "customer_type_list_01",
                uniqueId: "customer_type_list_01",
                title: "Customer Type List",
                path: "/customertypelist",
              },
              {
                _id: "third_party_customers_01",
                id: "third_party_customers_01",
                uniqueId: "third_party_customers_01",
                title: "Third-Party Customers",
                path: "/thirdpartycustomer",
              },
              {
                _id: "card_terminal_list_01",
                id: "card_terminal_list_01",
                uniqueId: "card_terminal_list_01",
                title: "Card Terminal List",
                path: "/cardterminallist",
              },
            ],
          },
          {
            _id: "kitchen_setting_01",
            id: "kitchen_setting_01",
            uniqueId: "kitchen_setting_01",
            title: "Kitchen Setting",
            isModule: false,
            subSubModule: [
              {
                _id: "kitchen_list_01",
                id: "kitchen_list_01",
                uniqueId: "kitchen_list_01",
                title: "Kitchen List",
                path: "/kitchenlist",
              },
              {
                _id: "kitchen_assign_01",
                id: "kitchen_assign_01",
                uniqueId: "kitchen_assign_01",
                title: "Kitchen Assign",
                path: "/kitchenassign",
              },
              {
                _id: "kitchen_dashboard_setting_01",
                id: "kitchen_dashboard_setting_01",
                uniqueId: "kitchen_dashboard_setting_01",
                title: "Kitchen Dashboard Setting",
                path: "/kitchendashboardsetting",
              },
            ],
          },
          {
            _id: "unit_measurement_01",
            id: "unit_measurement_01",
            uniqueId: "unit_measurement_01",
            title: "Unit Measurement",
            isModule: false,
            subSubModule: [
              {
                _id: "unit_measurement_list_01",
                id: "unit_measurement_list_01",
                uniqueId: "unit_measurement_list_01",
                title: "Unit Measurement List",
                path: "/unitmeasurementlist",
              },
              {
                _id: "ingredient_list_01",
                id: "ingredient_list_01",
                uniqueId: "ingredient_list_01",
                title: "Ingredient List",
                path: "/ingredientlist",
              },
            ],
          },
          {
            _id: "sms_setting_01",
            id: "sms_setting_01",
            uniqueId: "sms_setting_01",
            title: "SMS Setting",
            isModule: false,
            subSubModule: [
              {
                _id: "sms_configuration_01",
                id: "sms_configuration_01",
                uniqueId: "sms_configuration_01",
                title: "SMS Configuration",
                path: "/smsconfiguration",
              },
              {
                _id: "sms_template_01",
                id: "sms_template_01",
                uniqueId: "sms_template_01",
                title: "SMS Template",
                path: "/smstemplate",
              },
            ],
          },
          {
            _id: "bank_01",
            id: "bank_01",
            uniqueId: "bank_01",
            title: "Bank",
            isModule: false,
            subSubModule: [
              {
                _id: "bank_list_01",
                id: "bank_list_01",
                uniqueId: "bank_list_01",
                title: "Bank List",
                path: "/banklist",
              },
              {
                _id: "bank_transaction_01",
                id: "bank_transaction_01",
                uniqueId: "bank_transaction_01",
                title: "Bank Transaction",
                path: "/banktransaction",
              },
            ],
          },
          {
            _id: "language_01",
            id: "language_01",
            uniqueId: "language_01",
            title: "Language",
            path: "/language",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "application_setting_01",
            id: "application_setting_01",
            uniqueId: "application_setting_01",
            title: "Application Setting",
            path: "/applicationsetting",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "app_setting_01",
            id: "app_setting_01",
            uniqueId: "app_setting_01",
            title: "App Setting",
            path: "/serversetting",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "factory_reset_01",
            id: "factory_reset_01",
            uniqueId: "factory_reset_01",
            title: "Factory Reset",
            path: "/factoryreset",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "currency_01",
            id: "currency_01",
            uniqueId: "currency_01",
            title: "Currency",
            path: "/currency",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "country_01",
            id: "country_01",
            uniqueId: "country_01",
            title: "Country",
            path: "/country",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "state_01",
            id: "state_01",
            uniqueId: "state_01",
            title: "State",
            path: "/state",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "city_01",
            id: "city_01",
            uniqueId: "city_01",
            title: "City",
            path: "/city",
            isModule: false,
            subSubModule: [],
          },
          {
            _id: "commission_01",
            id: "commission_01",
            uniqueId: "commission_01",
            title: "Commission",
            path: "/commission",
            isModule: false,
            subSubModule: [],
          },
        ],
        uniqueId: "66daafd7b1796c15ed5a9188",
        id: "66daafd7b1796c15ed5a9188",
        title: "Setting",
      },
    ],
  },
};
